os:
  - linux
  - osx

language: ruby
rvm:
  - 2.0
  - 2.2
  - 2.3
  - 2.5
  - 2.7
  - jruby-9.1.7.0

gemfile:
  - testing/gemfiles/cuke_modeler1.gemfile
  - testing/gemfiles/cuke_modeler2.gemfile
  - testing/gemfiles/cuke_modeler3.gemfile

matrix:
  exclude:
    # Older versions of Ruby don't seem to work on Travis CI for OSX. The Linux
    # testing is probably good enough for the older versions.
    - rvm: 2.0
      os: osx
    - rvm: 2.2
      os: osx
    - rvm: 2.3
      os: osx
      # CukeModeler 3.x requires at least Ruby 2.3
    - rvm: 2.0
      gemfile: testing/gemfiles/cuke_modeler3.gemfile
    - rvm: 2.2
      gemfile: testing/gemfiles/cuke_modeler3.gemfile


script: bundle exec rake cuke_slicer:ci_build
